iapiConf = {"casinoname":"calienteclub","loginServer":"login.caliente.mx","imsLoginDomain":"caliente.mx","clientSkin":"calienteclub","clientType":"casino","clientPlatform":"flash","systemId":"45","serviceType":"GamePlay","loginDomainRetryCount":"2","loginDomainRequestTimeout":"30","loginDomainRetryInterval":"1","fitToPlaySubmissionRequired":"0","onlypostrequestsforlogout":"1","redirectUrl":"/integrationRedirect.html","clientUrl_casino":"https://static.caliente.mx/banner/casinoclient.html","safariSyncDisabled":"1","loggedInExpiry":"600000"};
 var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";
var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var f=e[g];if(!(f in d))return;d=d[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(f){return f instanceof e?f:new e(function(h,k){h(f)})}if(a&&(!($jscomp.FORCE_POLYFILL_PROMISE||$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION&&"undefined"===typeof $jscomp.global.PromiseRejectionEvent)||!$jscomp.global.Promise||-1===$jscomp.global.Promise.toString().indexOf("[native code]")))return a;b.prototype.asyncExecute=function(f){if(null==this.batch_){this.batch_=[];var h=this;this.asyncExecuteFunction(function(){h.executeBatch_()})}this.batch_.push(f)};
var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(f){d(f,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var f=this.batch_;this.batch_=[];for(var h=0;h<f.length;++h){var k=f[h];f[h]=null;try{k()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(f){this.asyncExecuteFunction(function(){throw f;})};var e=function(f){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];this.isRejectionHandled_=!1;var h=this.createResolveAndReject_();
try{f(h.resolve,h.reject)}catch(k){h.reject(k)}};e.prototype.createResolveAndReject_=function(){function f(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:f(this.resolveTo_),reject:f(this.reject_)}};e.prototype.resolveTo_=function(f){if(f===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof e)this.settleSameAsPromise_(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.resolveToNonPromiseObj_(f):
this.fulfill_(f)}};e.prototype.resolveToNonPromiseObj_=function(f){var h=void 0;try{h=f.then}catch(k){this.reject_(k);return}"function"==typeof h?this.settleSameAsThenable_(h,f):this.fulfill_(f)};e.prototype.reject_=function(f){this.settle_(2,f)};e.prototype.fulfill_=function(f){this.settle_(1,f)};e.prototype.settle_=function(f,h){if(0!=this.state_)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.state_);this.state_=f;this.result_=h;2===this.state_&&this.scheduleUnhandledRejectionCheck_();
this.executeOnSettledCallbacks_()};e.prototype.scheduleUnhandledRejectionCheck_=function(){var f=this;d(function(){if(f.notifyUnhandledRejection_()){var h=$jscomp.global.console;"undefined"!==typeof h&&h.error(f.result_)}},1)};e.prototype.notifyUnhandledRejection_=function(){if(this.isRejectionHandled_)return!1;var f=$jscomp.global.CustomEvent,h=$jscomp.global.Event,k=$jscomp.global.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):
"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=$jscomp.global.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.result_;return k(f)};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var f=0;f<this.onSettledCallbacks_.length;++f)g.asyncExecute(this.onSettledCallbacks_[f]);this.onSettledCallbacks_=null}};var g=new b;e.prototype.settleSameAsPromise_=function(f){var h=this.createResolveAndReject_();
f.callWhenSettled_(h.resolve,h.reject)};e.prototype.settleSameAsThenable_=function(f,h){var k=this.createResolveAndReject_();try{f.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};e.prototype.then=function(f,h){function k(n,p){return"function"==typeof n?function(r){try{l(n(r))}catch(t){m(t)}}:p}var l,m,q=new e(function(n,p){l=n;m=p});this.callWhenSettled_(k(f,l),k(h,m));return q};e.prototype.catch=function(f){return this.then(void 0,f)};e.prototype.callWhenSettled_=function(f,h){function k(){switch(l.state_){case 1:f(l.result_);
break;case 2:h(l.result_);break;default:throw Error("Unexpected state: "+l.state_);}}var l=this;null==this.onSettledCallbacks_?g.asyncExecute(k):this.onSettledCallbacks_.push(k);this.isRejectionHandled_=!0};e.resolve=c;e.reject=function(f){return new e(function(h,k){k(f)})};e.race=function(f){return new e(function(h,k){for(var l=$jscomp.makeIterator(f),m=l.next();!m.done;m=l.next())c(m.value).callWhenSettled_(h,k)})};e.all=function(f){var h=$jscomp.makeIterator(f),k=h.next();return k.done?c([]):new e(function(l,
m){function q(r){return function(t){n[r]=t;p--;0==p&&l(n)}}var n=[],p=0;do n.push(void 0),p++,c(k.value).callWhenSettled_(q(n.length-1),m),k=h.next();while(!k.done)})};return e},"es6","es3");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,g){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=$jscomp.checkStringArgs(this,b,"startsWith");b+="";var e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<g&&c<e;)if(d[c++]!=b[f++])return!1;return f>=g}},"es6","es3");
function replaceImsDomain(){if(iapiConf&&iapiConf.imsLoginDomain)for(var a in iapiConf){var b=iapiConf[a];"string"===typeof b&&0<=b.indexOf("http")&&0<b.indexOf("$imsLoginDomain")&&(b=b.replace("$imsLoginDomain",iapiConf.imsLoginDomain),iapiConf[a]=b)}}replaceImsDomain();
var iapiVersion="_version_",iapiERR_OK=0,iapiERR_NOK=-1,iapiERR_BLOCKED=-2,iapiCALLOUT_LOGIN="Login",iapiCALLOUT_EMAILLOGIN="EmailLogin",iapiCALLOUT_TEMPORARYTOKEN="GetTemporaryAuthenticationToken",iapiCALLOUT_LOGINANDGETTEMPTOKEN="LoginAndGetTempToken",iapiCALLOUT_EMAILLOGINANDGETTEMPTOKEN="EmailLoginAndGetTempToken",iapiCALLOUT_SESSIONVALIDATION="ValidateLoginSession",iapiCALLOUT_MESSAGES="GetWaitingMessages",iapiCALLOUT_SUBMITDIALOG="SubmitDialog",iapiCALLOUT_FORGOTPASSWORD="ForgotPassword",iapiCALLOUT_STARTFORGOTEMAIL=
"StartForgotEamil",iapiCALLOUT_COMPLETEFORGOTEMAIL="CompleteForgotEmail",iapiCALLOUT_ONLINEFORGOTPASSWORD="OnlineForgotPassword",iapiCALLOUT_GETLOGGEDINPLAYER="GetLoggedInPlayer",iapiCALLOUT_KEEPALIVE="KeepAlive",iapiCALLOUT_LOGOUT="Logout",iapiCALLOUT_GETURLS="GetUrls",iapiEVENT_TIMER=10,STOCK_AUTH_PHONE_NUMBER="pinAuth888",iapiUsername=null,iapiPassword=null,iapiEmail=null,iapiAdminUsername=null,iapiRealMode=1,iapiAuthenticationType=null,iapiDivname="iapidiv",iapiIframename="iapiiframe",iapiRealCookieIframe=
"iapirealcookieiframe",iapiFunCookieIframe="iapifuncookieiframe",iapiGetLoggedInPlayerRequestIdReal=1234567890,iapiGetLoggedInPlayerRequestIdFun=9876543210,iapiClientParams=[],iapiWaitingMessagesId=0,iapiRememberMeLogin=null,iapiCalloutFunctions=[],iapiRequestIds=[],iapiLoginSuccess=!1,iapiSessionValid=0,iapiNextLogin=null,iapiLoginModeDownload=!1,iapiLoginModeFlash=!1,iapiFlashLoginClientType=null,iapiFlashLoginGameType=null,iapiMessagesSupported=!1,iapiMessagesAnswered=!1,iapiLoginTypes=Object.freeze({SESSION_TOKEN:"sessionToken",
CRYPTO_TOKEN:"cryptoToken",EXTERNAL_TOKEN:"externalToken",ADMIN_USERNAME:"adminUsername",NICKNAME:"nickname",EMAIL:"email",TOKEN_CODE:"tokenCode",PRINTED_TOKEN_CODE:"printedTokenCode",USERNAME_AND_PIN:"usernameAndPin",TOKEN_CODE_AND_PASS:"tokenCodeAndPass"});function iapiLogin(a,b,c,d,e){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiConf.authenticationType;iapiBaseLogin(a,b,c,d,e);return iapiERR_OK}
function iapiEmailLogin(a,b,c,d,e){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.EMAIL;iapiBaseLogin(a,b,c,d,e);return iapiERR_OK}function iapiLoginExternalToken(a,b,c){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.EXTERNAL_TOKEN;iapiBaseLogin(null,a,b,c);return iapiERR_OK}
function iapiLoginUsernameExternalToken(a,b,c,d){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.EXTERNAL_TOKEN;iapiBaseLogin(a,b,c,d);return iapiERR_OK}function iapiLoginAdminUsername(a,b,c,d,e){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.ADMIN_USERNAME;iapiAdminUsername=a;iapiBaseLogin(e,b,c,d);return iapiERR_OK}
function iapiLoginSessionToken(a,b,c){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.SESSION_TOKEN;iapiBaseLogin(null,a,b,c);return iapiERR_OK}function iapiLoginCryptoToken(a,b){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.CRYPTO_TOKEN;iapiBaseLogin(null,a,1,b);return iapiERR_OK}
function iapiLoginNickname(a,b,c,d){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.NICKNAME;iapiBaseLogin(a,b,c,d);return iapiERR_OK}function iapiLoginIdTokenCodeAndPin(a,b,c,d){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.TOKEN_CODE;iapiBaseLogin(a,b,1,c,d);return iapiERR_OK}
function iapiLoginPrintedIdTokenCodeAndPin(a,b,c,d){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.PRINTED_TOKEN_CODE;iapiBaseLogin(a,b,1,c,d);return iapiERR_OK}function iapiLoginUsernameAndPin(a,b,c,d){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.USERNAME_AND_PIN;iapiBaseLogin(a,b,1,c,d);return iapiERR_OK}
function iapiLoginIdTokenCodeAndPassword(a,b,c){iapiLoginModeFlash=iapiLoginModeDownload=!1;iapiAuthenticationType=iapiLoginTypes.TOKEN_CODE_AND_PASS;iapiBaseLogin(a,b,1,c);return iapiERR_OK}
function iapiLaunchClient(a,b,c,d,e,g){var f=iapiConf["clientUrl_"+a];if(f){b&&(f=iapiAddUrlParams(f,"game="+b));c&&(f=iapiAddUrlParams(f,"preferedmode="+c));iapiClientParams["clientParams_"+a]&&(f=iapiAddUrlParams(f,iapiClientParams["clientParams_"+a]));if(0<=f.indexOf("$domain")||0<=f.indexOf("<domain>"))c=getCurrentDomain(),f=f.replace("$domain",c),f=f.replace("<domain>",c);if(iapiLoginModeFlash){document.location=f;return}c="width=800,height=600";if(void 0!=e&&void 0!=g)if(-1==e&&-1==g){c="";
if("Microsoft Internet Explorer"==navigator.appName||0<=navigator.userAgent.indexOf("Safari")&&0>navigator.userAgent.indexOf("Chrome"))c="left=0,top=0,";b=screen.width;e=screen.height;void 0!=screen.availWidth&&(b=screen.availWidth,e=screen.availHeight);"number"==typeof innerWidth&&"number"==typeof outerWidth&&(b-=outerWidth-innerWidth,e-=outerWidth-innerWidth);c+="width="+b+",height="+e}else c="width="+e+",height="+g;else iapiConf["windowSize_"+a]&&(b=iapiConf["windowSize_"+a][b],void 0==b&&(b=iapiConf["windowSize_"+
a]["default"]),void 0!=b&&iapiConf.windowSizes[b]&&(c=iapiConf.windowSizes[b]));if(null!=d&&0<d.length){if(b=document.getElementById(d))return b.src=f,iapiERR_OK}else d="";b="toolbar=no,menubar=no,scrollbars=no,resizable=no";iapiConf["windowParams_"+a]&&(b=iapiConf["windowParams_"+a]);windowParams=c+","+b;a=window.open(f,d,windowParams);return null==a||a.closed?iapiERR_BLOCKED:iapiERR_OK}return iapiERR_NOK}function iapiSetClientParams(a,b){iapiClientParams["clientParams_"+a]=b}
function NoSystemId(){}NoSystemId.prototype.toString=function(){return""};var noSystemId=new NoSystemId;
function iapiRequestTemporaryToken(a,b,c,d){var e="GetTemporaryAuthenticationToken.php?casinoname="+iapiConf.casinoname;e=void 0!=c?e+("&serviceType="+c):e+("&serviceType="+iapiConf.serviceType);0===b||0===parseInt(b)?b=void 0:b?(new String(b)).toString()||(b=void 0):b=iapiConf.systemId;b&&(e+="&systemId="+b);d&&(e+="&inheritance="+d);void 0!=a&&(e+="&realMode="+a);iapiMakeRedirectRequest(e,null,iapiCALLOUT_TEMPORARYTOKEN);return iapiERR_OK}
function iapiLoginAndGetTempToken(a,b,c,d,e,g,f,h){iapiClearRedirectRequests(iapiCALLOUT_LOGINANDGETTEMPTOKEN,c);0===e||0===parseInt(e)?e=void 0:e?(new String(e)).toString()||(e=void 0):e=iapiConf.systemId;g||(g=iapiConf.serviceType);d&&iapiSetLanguageCode(d);c="LoginAndGetTempToken.php?casinoname="+iapiConf.casinoname+"&realMode="+c+"&serviceType="+g;e&&(c+="&systemId="+e);1==f&&(c+="&rememberMeLogin=1");h&&(c+="&inheritance="+h);f=[];iapiAuthenticationType=iapiConf.authenticationType;iapiAuthenticationType==
iapiLoginTypes.EXTERNAL_TOKEN?(a&&(f.username=a),f.externalToken=b,iapiConf.italyAamsSessionCode&&(f.italyAamsSessionCode=iapiConf.italyAamsSessionCode),iapiConf.italyParticipationCode&&(f.italyParticipationCode=iapiConf.italyParticipationCode),iapiConf.italyExternalGameTableSessionCode&&(f.italyExternalGameTableSessionCode=iapiConf.italyExternalGameTableSessionCode)):iapiAuthenticationType==iapiLoginTypes.SESSION_TOKEN?f.sessionToken=b:iapiAuthenticationType==iapiLoginTypes.ADMIN_USERNAME?(a&&(f.adminUsername=
a),f.externalToken=b):iapiAuthenticationType==iapiLoginTypes.NICKNAME?(f.nickname=a,f.password=b,f.systemId=e):iapiAuthenticationType==iapiLoginTypes.EMAIL?(a&&(f.email=a),f.password=b,iapiConf.iovationBlackbox&&(f.iovationBlackbox=iapiConf.iovationBlackbox)):(f.username=a,f.password=b,iapiConf.iovationBlackbox&&(f.iovationBlackbox=iapiConf.iovationBlackbox),iapiConf.italyAamsSessionCode&&(f.italyAamsSessionCode=iapiConf.italyAamsSessionCode),iapiConf.italyParticipationCode&&(f.italyParticipationCode=
iapiConf.italyParticipationCode),iapiConf.italyExternalGameTableSessionCode&&(f.italyExternalGameTableSessionCode=iapiConf.italyExternalGameTableSessionCode));iapiAddClientHintsAndContinue(c,f,iapiCALLOUT_LOGINANDGETTEMPTOKEN);return iapiERR_OK}function iapiEmailLoginAndGetTempToken(a,b,c,d,e,g,f,h){iapiConf.authenticationType=iapiLoginTypes.EMAIL;iapiLoginAndGetTempToken(a,b,c,d,e,g,f,h);iapiConf.authenticationType=null}
function iapiLoginExternalTokenAndGetTempToken(a,b,c,d,e,g,f,h){iapiConf.authenticationType=iapiLoginTypes.EXTERNAL_TOKEN;iapiLoginAndGetTempToken(a,b,c,d,e,g,f,h);iapiConf.authenticationType=null}function iapiDownloadLogin(a,b,c,d){iapiAuthenticationType=null;iapiLoginModeDownload=!0;iapiLoginModeFlash=!1;iapiBaseLogin(a,b,c,d);return iapiERR_OK}
function iapiDownloadEmailLogin(a,b,c,d){iapiAuthenticationType=iapiLoginTypes.EMAIL;iapiLoginModeDownload=!0;iapiLoginModeFlash=!1;iapiBaseLogin(a,b,c,d);return iapiERR_OK}function iapiFlashLogin(a,b,c,d,e,g){iapiAuthenticationType=null;iapiLoginModeFlash=!0;iapiLoginModeDownload=!1;iapiFlashLoginClientType=e;iapiFlashLoginGameType=g;iapiBaseLogin(a,b,c,d);return iapiERR_OK}
function iapiFlashEmailLogin(a,b,c,d,e,g){iapiAuthenticationType=iapiLoginTypes.EMAIL;iapiLoginModeFlash=!0;iapiLoginModeDownload=!1;iapiFlashLoginClientType=e;iapiFlashLoginGameType=g;iapiBaseLogin(a,b,c,d);return iapiERR_OK}
function iapiLogout(a,b,c,d){iapiEmail=iapiPassword=iapiUsername=null;iapiClearRedirectRequests(iapiCALLOUT_LOGIN,b);var e=[];1==b?iapiWriteClientCookie("loginSuccess=0&errorCode=0&expire=-1",1):iapiWriteClientCookie("loginSuccess=0&errorCode=0&expire=-1",0);void 0==c&&(c=1==a?"all":"this");var g="Logout.php?allSessions="+a+"&casinoname="+iapiConf.casinoname+"&behaviour="+c;e.allSessions=a;e.casinoname=iapiConf.casinoname;e.behaviour=c;void 0!=b&&(g+="&realMode="+b,e.realMode=b);1==d&&(g+="&invalidateRememberMe=1",
e.invalidateRememberMe=1);iapiConf.onlypostrequestsforlogout?iapiMakeRedirectRequest(g,e,iapiCALLOUT_LOGOUT):iapiMakeRedirectRequest(g,null,iapiCALLOUT_LOGOUT);return iapiERR_OK}function iapiSetCallout(a,b){iapiCalloutFunctions[a]=b;return iapiERR_OK}
function iapiGetWaitingMessages(a,b){iapiClearRedirectRequests(iapiCALLOUT_MESSAGES,0);iapiClearRedirectRequests(iapiCALLOUT_MESSAGES,1);a||(a="login,bonus,alert");iapiMakeRedirectRequest("GetWaitingMessages.php?messageTypes="+a+"&casinoname="+iapiConf.casinoname+"&realMode="+b,null,iapiCALLOUT_MESSAGES);return iapiERR_OK}
function iapiAcceptPendingLimits(a,b){var c="SubmitDialog.php?dialogType=AcceptPendingLimits&casinoname="+iapiConf.casinoname;void 0!=b&&(c+="&realMode="+b);b=[];b.action=a;iapiMakeRedirectRequest(c,b,iapiCALLOUT_SUBMITDIALOG);return iapiERR_OK}
function iapiBonusConfirmation(a,b,c){var d="SubmitDialog.php?dialogType=BonusConfirmation&casinoname="+iapiConf.casinoname;void 0!=c&&(d+="&realMode="+c);c=[];c.bonusIdentifier=a;c.accept=b?1:0;iapiMakeRedirectRequest(d,c,iapiCALLOUT_SUBMITDIALOG);return iapiERR_OK}
function iapiValidateTCVersion(a,b,c){var d="ValidateLoginSession.php?validationType=TCVersion&casinoname="+iapiConf.casinoname;void 0!=c&&(d+="&realMode="+c);c=[];c.termVersionReference=a;c.accept=b?1:0;iapiMakeRedirectRequest(d,c,iapiCALLOUT_SESSIONVALIDATION);return iapiERR_OK}
function iapiValidateGeolocation(a,b,c,d,e){var g=[];g.latitude=a;g.longitude=b;g.geopacket=c;g.transactionId=d;g.error=e;for(var f in g)null!==g[f]&&void 0!==g[f]||delete g[f];iapiMakeRedirectRequest("ValidateLoginSession.php?validationType=Geolocation&casinoname="+iapiConf.casinoname+"&realMode=1",g,iapiCALLOUT_SESSIONVALIDATION);return iapiERR_OK}
function iapiValidatePasswordChange(a,b,c,d){var e="ValidateLoginSession.php?validationType=PasswordChange&casinoname="+iapiConf.casinoname;void 0!=d&&(e+="&realMode="+d);d=[];d.oldPassword=a;d.newPassword=b;c&&(d.changePassword=1);iapiMakeRedirectRequest(e,d,iapiCALLOUT_SESSIONVALIDATION);return iapiERR_OK}
function iapiValidateConfirmationToken(a,b){var c="ValidateLoginSession.php?validationType=ConfirmationToken&casinoname="+iapiConf.casinoname;b&&(c+="&realMode="+b);b=[];b.parameter=a;iapiMakeRedirectRequest(c,b,iapiCALLOUT_SESSIONVALIDATION);return iapiERR_OK}
function iapiValidateBirthdateToken(a,b){var c="ValidateLoginSession.php?validationType=Birthdate&casinoname="+iapiConf.casinoname;b&&(c+="&realMode="+b);b=[];b.birthdate=a;iapiMakeRedirectRequest(c,b,iapiCALLOUT_SESSIONVALIDATION);return iapiERR_OK}
function iapiValidateActivationCode(a,b){var c="ValidateLoginSession.php?validationType=ActivationCode&casinoname="+iapiConf.casinoname;b&&(c+="&realMode="+b);b=[];b.activationCode=a;iapiMakeRedirectRequest(c,b,iapiCALLOUT_SESSIONVALIDATION);return iapiERR_OK}function iapiValidatePinChange(a,b){var c="ValidateLoginSession.php?validationType=PINChange&casinoname="+iapiConf.casinoname+"&realMode=1",d=[];d.oldPin=a;d.newPin=b;iapiMakeRedirectRequest(c,d,iapiCALLOUT_SESSIONVALIDATION)}
function iapiValidatePinToken(a){var b="ValidateLoginSession.php?validationType=PINToken&casinoname="+iapiConf.casinoname+"&realMode=1",c=[];c.pin=a;iapiMakeRedirectRequest(b,c,iapiCALLOUT_SESSIONVALIDATION)}function iapiValidatePassword(a,b){var c="ValidateLoginSession.php?validationType=LoginNameAndPassword&casinoname="+iapiConf.casinoname+"&realMode=1",d=[];d.password=a;d.loginName=b;iapiMakeRedirectRequest(c,d,iapiCALLOUT_SESSIONVALIDATION)}
function iapiValidateTwoFactorToken(a,b,c){var d="ValidateLoginSession.php?validationType=TwoFactor&casinoname="+iapiConf.casinoname+"&realMode=1",e=[];e["2faToken"]=a;e.trustDevice=b;e.deviceName=c;iapiMakeRedirectRequest(d,e,iapiCALLOUT_SESSIONVALIDATION)}function iapiValidateFitToPlayToken(a){var b="ValidateLoginSession.php?validationType=FitToPlay&casinoname="+iapiConf.casinoname+"&realMode=1",c=[];c.fitToPlay=a;iapiMakeRedirectRequest(b,c,iapiCALLOUT_SESSIONVALIDATION)}
function iapiForgotPassword(a,b,c,d,e,g,f){d="ForgotPassword.php?casinoname="+iapiConf.casinoname+"&realMode="+d;var h=[];h.username=a;h.email=b;h.birthDate=c;e&&(h.verificationAnswer=e);g&&(h.passwordRecoveryDestinationLink=g);f&&(h.notificationChannels=f);iapiMakeRedirectRequest(d,h,iapiCALLOUT_FORGOTPASSWORD);return iapiERR_OK}
function iapiStartForgotEmail(a,b,c,d,e){c="StartForgotEmail.php?casinoname="+iapiConf.casinoname+"&realMode="+c;var g=[];g.cellphone=a;g.birthdate=b;g.lastName=d;g.personalId=e;iapiMakeRedirectRequest(c,g,iapiCALLOUT_STARTFORGOTEMAIL);return iapiERR_OK}function iapiCompleteForgotEmail(a,b,c){b="CompleteForgotEmail.php?casinoname="+iapiConf.casinoname+"&realMode="+b;var d=[];d.token=a;c&&(d.pin=c);iapiMakeRedirectRequest(b,d,iapiCALLOUT_COMPLETEFORGOTEMAIL);return iapiERR_OK}
function iapiOnlineForgotPassword(a,b,c,d,e,g,f,h){d="OnlineForgotPassword.php?casinoname="+iapiConf.casinoname+"&realMode="+d;var k=[];k.username=a;b&&(k.email=b);c&&(k.birthDate=c);e&&(k.verificationAnswer=e);g&&(k.newPassword=g);f&&(k.passwordRecoveryDestinationLink=f);h&&(k.notificationChannels=h);iapiMakeRedirectRequest(d,k,iapiCALLOUT_ONLINEFORGOTPASSWORD);return iapiERR_OK}
function iapiGetLoggedInPlayer(a){var b=iapiCALLOUT_GETLOGGEDINPLAYER;if(isStorageAvailable()){iapiCalloutFunctions[b="loggedInPlayerHandlerX"]=self.loggedInPlayerHandlerX;var c=getSessionKey("loggedInPlayer-recent"),d=window.sessionStorage.getItem(c);if(d&&(d=JSON.parse(d))&&Date.now()-d.time<(iapiConf.loggedInExpiry?parseInt(iapiConf.loggedInExpiry):26E4)&&(d.session==window.sessionStorage.getItem(getSessionKey("token"))||d.session==window.sessionStorage.getItem(getSessionKey("sessionRef"))))return setTimeout(function(){iapiCalloutFunctions[iapiCALLOUT_GETLOGGEDINPLAYER](d.resp)},
iapiEVENT_TIMER),iapiERR_OK;window.sessionStorage.removeItem(c)}iapiMakeRedirectRequest("GetLoggedInPlayer.php?casinoname="+iapiConf.casinoname+"&realMode="+a,null,b);return iapiERR_OK}function getSessionKey(a){return"pas["+iapiConf.casinoname+"][real]["+a+"]"}
function loggedInPlayerHandlerX(a){if(isStorageAvailable()){var b=getSessionKey("loggedInPlayer-recent");if(a.username){var c={};c.resp=a;c.time=Date.now();c.session=window.sessionStorage.getItem(getSessionKey("token"));c.session||(c.session=window.sessionStorage.getItem(getSessionKey("sessionRef")));c=JSON.stringify(c);window.sessionStorage.setItem(b,c)}else window.sessionStorage.removeItem(b)}if(iapiCalloutFunctions[iapiCALLOUT_GETLOGGEDINPLAYER])iapiCalloutFunctions[iapiCALLOUT_GETLOGGEDINPLAYER](a)}
function iapiKeepAlive(a,b){a="KeepAlive.php?casinoname="+iapiConf.casinoname+"&realMode="+a;b&&(a+="&millisFromLastAction="+b);iapiMakeRedirectRequest(a,null,iapiCALLOUT_KEEPALIVE);return iapiERR_OK}function iapiGetUrls(a){iapiMakeRedirectRequest("GetUrls.php?casinoname="+iapiConf.casinoname+"&realMode=1&urlTypeList="+a,null,iapiCALLOUT_GETURLS);return iapiERR_OK}function iapiSetAuthenticationType(a){iapiConf.authenticationType=a}function iapiSetClientSkin(a){iapiConf.clientSkin=a}
function iapiSetClientType(a){iapiConf.clientType=a}function iapiSetClientUrl(a,b){iapiConf["clientUrl_"+a]=b}function iapiSetClientVersion(a){iapiConf.clientVersion=a}function iapiSetClientChannel(a){iapiConf.clientChannel=a}function iapiSetGameType(a){iapiConf.gameType=a}function iapiSetGameTypePrefix(a){iapiConf.gameTypePrefix=a}function iapiSetLaunchAlias(a){iapiConf.launchAlias=a}function iapiSetClientPlatform(a){iapiConf.clientPlatform=a}function iapiSetSystemId(a){iapiConf.systemId=a}
function iapiSetServiceType(a){iapiConf.serviceType=a}function iapiSetLanguageCode(a){iapiConf.languageCode=a}function iapiSetCallId(a){iapiConf.callId=a}function iapiSetDeliveryPlatform(a){iapiConf.deliveryPlatform=a}function iapiSetDeviceBrowser(a){iapiConf.deviceBrowser=a}function iapiSetOsName(a){iapiConf.osName=a}function iapiSetOsVersion(a){iapiConf.osVersion=a}function iapiSetDeviceId(a){iapiConf.deviceId=a}function iapiSetDeviceType(a){iapiConf.deviceType=a}
function iapiSetDeviceFamily(a){iapiConf.deviceFamily=a}function iapiSetSoftSerial(a){iapiConf.softSerial=a}function iapiSetIovationBlackbox(a){iapiConf.iovationBlackbox=a}function iapiSetItalyAamsSessionCode(a){iapiConf.italyAamsSessionCode=a}function iapiSetItalyParticipationCode(a){iapiConf.italyParticipationCode=a}function iapiSetItalyExternalGameTableSessionCode(a){iapiConf.italyExternalGameTableSessionCode=a}function iapiEnableUserErrors(){iapiConf.errorLevel=1}
function iapiCallbackWaitingMessages(a){var b=iapiGetRequest(iapiWaitingMessagesId);if(b){var c={errorCode:6,errorText:"Invalid response.",playerMessage:""};a?c=a.errorCode?{errorCode:a.errorCode,errorText:a.errorText,playerMessage:a.playerMessage}:null:a=c;if(c&&6==c.errorCode&&b[3].length<iapiConf.loginDomainRetryCount){c=(new Date).getTime()+Math.round(1E6*Math.random());var d=setTimeout("iapiRequestFailed("+c+")",1E3*iapiConf.loginDomainRetryInterval);iapiRegisterRequestId(c,iapiCALLOUT_MESSAGES,
d,b[3],b[4],b[5])}else iapiCalloutFunctions[iapiCALLOUT_MESSAGES]&&setTimeout(function(){iapiCalloutFunctions[iapiCALLOUT_MESSAGES](a)},iapiEVENT_TIMER)}}
function iapiBaseLogin(a,b,c,d,e){if(iapiHasRedirectRequest(iapiCALLOUT_LOGIN)&&iapiRealMode!=c)return iapiNextLogin=[a,b,c,d,e],iapiERR_OK;iapiAuthenticationType==iapiLoginTypes.EMAIL?iapiEmail=a:iapiUsername=a;iapiPassword=b;iapiRealMode=1==c?1:0;d&&iapiSetLanguageCode(d);iapiRememberMeLogin=e;iapiLoginSuccess=!1;iapiWriteClientCookie("loginInProgress=1",iapiRealMode);iapiContinueLogin()}
function iapiContinueLogin(){iapiClearRedirectRequests(iapiCALLOUT_LOGIN,0);iapiClearRedirectRequests(iapiCALLOUT_LOGIN,1);var a="Login.php?casinoname="+iapiConf.casinoname;a=1==iapiRealMode?a+"&realMode=1":a+"&realMode=0";1==iapiRememberMeLogin&&(a+="&rememberMeLogin=1");var b=[];iapiAuthenticationType==iapiLoginTypes.EXTERNAL_TOKEN?(iapiUsername&&(b.username=iapiUsername),b.externalToken=iapiPassword,iapiConf.italyAamsSessionCode&&(b.italyAamsSessionCode=iapiConf.italyAamsSessionCode),iapiConf.italyParticipationCode&&
(b.italyParticipationCode=iapiConf.italyParticipationCode),iapiConf.italyExternalGameTableSessionCode&&(b.italyExternalGameTableSessionCode=iapiConf.italyExternalGameTableSessionCode)):iapiAuthenticationType==iapiLoginTypes.EMAIL?(iapiEmail&&(b.email=iapiEmail),b.password=iapiPassword,iapiConf.iovationBlackbox&&(b.iovationBlackbox=iapiConf.iovationBlackbox)):iapiAuthenticationType==iapiLoginTypes.SESSION_TOKEN?b.sessionToken=iapiPassword:iapiAuthenticationType==iapiLoginTypes.CRYPTO_TOKEN?b.cryptoToken=
iapiPassword:iapiAuthenticationType==iapiLoginTypes.ADMIN_USERNAME?(iapiAdminUsername&&(b.adminUsername=iapiAdminUsername),b.username=iapiUsername,b.externalToken=iapiPassword):iapiAuthenticationType==iapiLoginTypes.NICKNAME?(b.nickname=iapiUsername,b.password=iapiPassword,b.systemId=iapiConf.systemId):iapiAuthenticationType==iapiLoginTypes.TOKEN_CODE?(b.tokenCode=iapiUsername,b.pin=iapiPassword,b.systemId=iapiConf.systemId):iapiAuthenticationType==iapiLoginTypes.PRINTED_TOKEN_CODE?(b.printedTokenCode=
iapiUsername,b.pin=iapiPassword,b.systemId=iapiConf.systemId):iapiAuthenticationType==iapiLoginTypes.USERNAME_AND_PIN?(b.username=iapiUsername,b.phone=STOCK_AUTH_PHONE_NUMBER,b.pin=iapiPassword,b.systemId=iapiConf.systemId):iapiAuthenticationType==iapiLoginTypes.TOKEN_CODE_AND_PASS?(b.tokenCode=iapiUsername,b.password=iapiPassword,b.systemId=iapiConf.systemId):(b.username=iapiUsername,b.password=iapiPassword,iapiConf.iovationBlackbox&&(b.iovationBlackbox=iapiConf.iovationBlackbox),iapiConf.italyAamsSessionCode&&
(b.italyAamsSessionCode=iapiConf.italyAamsSessionCode),iapiConf.italyParticipationCode&&(b.italyParticipationCode=iapiConf.italyParticipationCode),iapiConf.italyExternalGameTableSessionCode&&(b.italyExternalGameTableSessionCode=iapiConf.italyExternalGameTableSessionCode));iapiAddClientHintsAndContinue(a,b,iapiCALLOUT_LOGIN);return iapiERR_OK}
function iapiAddClientHintsAndContinue(a,b,c){if(isDeviceAtlasEnabled())try{Promise.all(deviceAtlasScripts).then(function(){clientHintHeaders.then(function(d){try{b.clientHints=JSON.stringify(d),b.deviceAtlasProperties=DeviceAtlas.getPropertiesAsString()}finally{iapiMakeRedirectRequest(a,b,c)}})}).catch(function(){iapiMakeRedirectRequest(a,b,c)})}catch(d){iapiMakeRedirectRequest(a,b,c)}else iapiMakeRedirectRequest(a,b,c)}
function iapiWriteClientCookie(a,b){if(!iapiLoginModeDownload){var c=iapiConf.clientCookieUrl;c&&(0>c.indexOf("://")&&(c=location.protocol+"//"+c),a=c+"?"+a+"&casinoname="+iapiConf.casinoname+"&realMode="+b,c=iapiRealCookieIframe,0==b&&(c=iapiFunCookieIframe),iapiCreateDiv(iapiDivname),iapiCreateIframe(iapiDivname,c,"weLoveBaking"),iapiGet(c,a))}}
function iapiCreateDiv(a){if(!document.getElementById(a)){var b=document.createElement("div");b.setAttribute("id",a);b.setAttribute("style","DISPLAY:none;");document.body.appendChild(b)}}function resolveFrameName(a,b,c){return c==iapiCALLOUT_GETLOGGEDINPLAYER||"loggedInPlayerHandlerX"==c?a+"-"+c:b}
function iapiCreateIframe(a,b,c){var d=document.getElementById(a),e=c==iapiCALLOUT_GETLOGGEDINPLAYER||"loggedInPlayerHandlerX"==c;b=resolveFrameName(a,b,c);if(document.getElementById(b)){if(e)return b;d.removeChild(document.getElementById(b))}try{var g=document.createElement("<iframe name='"+b+"'>")}catch(f){g=document.createElement("iframe")}e&&(g.dataset.reusable=c);g.setAttribute("id",b);g.setAttribute("name",b);g.setAttribute("style","DISPLAY: none; LEFT: 0px; POSITION: absolute; TOP: 0px");g.setAttribute("width",
"0px");g.setAttribute("height","0px");g.setAttribute("border","0px");g.setAttribute("frameborder","0");d.appendChild(g);return null}
function iapiPost(a,b,c){a=encodeHTML(a);b=encodeURL(b);var d=document.getElementsByTagName("script")[0].getAttribute("nonce");b="<html><head></head><body><form id='formid' target='"+a+"' method='POST' action='"+b+"'>";for(var e in c)"function"!=typeof c[e]&&(b+="<input type='hidden' name='"+e+"' value='"+encodeHTML(c[e])+"'>");b+="</form><script type='text/javascript'";d&&(b+=" nonce="+d);iapiPostWindow(a,b+">setTimeout(function(){document.getElementById('formid').submit();},100);\x3c/script></body></html>")}
function iapiPostWindow(a,b){if(a=document.getElementById(a))try{a.contentWindow.document.open(),a.contentWindow.document.write(b),a.contentWindow.document.close()}catch(c){b="javascript:'<script>window.onload=function(){var ed=\\'"+escape(escape("<script>document.domain='"+document.domain+"';\x3c/script>"+b))+"\\';document.write(unescape(ed));document.close();};\x3c/script>'",a.src=b}}
function iapiMakeRedirectRequest(a,b,c,d){if(!d)d=[];else if(d.length>=iapiConf.loginDomainRetryCount||25<=d.length)return!1;var e=iapiConf.loginServer.split("|");if(d.length<e.length)for(var g in d){var f=d[g],h;for(h in e)if(e[h]==f&&"string"===typeof e[h]){e.splice(h,1);break}}a=iapiAppendContextParameters(a);var k=e[Math.floor(Math.random()*e.length)];d.push(k);requestUrl=getHttpProtocol()+"://"+k+"/"+a;var l=Date.now()+"x"+Math.round(1E6*Math.random());requestUrl=isPostMessagesDisabled()&&c==
iapiCALLOUT_MESSAGES?requestUrl+("&cacheBreaker="+(new Date).getTime()):requestUrl+("&redirectUrl="+escape(location.protocol+"//"+location.hostname+(location.port?":"+location.port:"")+(iapiConf.redirectUrl?iapiConf.redirectUrl:"/")+"#requestId="+l));1==iapiConf.errorLevel&&(requestUrl+="&errorLevel=1");e=setTimeout(function(){iapiRequestFailed(l)},1E3*iapiConf.loginDomainRequestTimeout);iapiRegisterRequestId(l,c,e,d,a,b);if(isPostMessagesDisabled()&&c==iapiCALLOUT_MESSAGES)iapiWaitingMessagesId=
l,iapiJsonp(requestUrl,"iapiCallbackWaitingMessages");else{iapiCreateDiv(iapiDivname);a=resolveFrameName(iapiDivname,iapiIframename+"_"+l,c);(d=iapiCreateIframe(iapiDivname,a,c))&&(a=d);var m=document.getElementById(a);m.dataset.requestId=l;iapiMessagesSupported||initMessageListener();if(isPostMessagesDisabled()){if(iapiMessagesSupported&&(requestUrl+="&messagesSupported=1",d&&iapiMessagesAnswered&&m.contentWindow.postMessage))return m.contentWindow.postMessage(c,getHttpProtocol()+"://"+k),!0}else if(iapiMessagesSupported){requestUrl+=
"&messagesSupported=1";var q={requestType:c,postParams:b,url:requestUrl,casino:iapiConf.casinoname,requestId:l};d?m.contentWindow.postMessage(q,getHttpProtocol()+"://"+k):(b=getHttpProtocol()+"://"+k+"/pasSetupPage.php?casino="+iapiConf.casinoname,m.contentWindow.location.replace(b),m.addEventListener("load",function(n){m.contentWindow.postMessage(q,getHttpProtocol()+"://"+k)}));return}b?iapiPost(a,requestUrl,b):iapiGet(a,requestUrl)}return!0}var storageAvailableResolved=0;
function isStorageAvailable(){if(storageAvailableResolved)return 0<storageAvailableResolved;try{return window.sessionStorage.setItem("test","test"),window.sessionStorage.removeItem("test"),checkCookieBuster(),0<(storageAvailableResolved=1)}catch(a){}return 0<(storageAvailableResolved=-1)}
function checkCookieBuster(){try{if(!(0>storageAvailableResolved)&&window.sessionStorage){var a=cookieBusterValue();a&&a!=window.sessionStorage.getItem("pasCookieBuster")&&(clearSessionStorage(window.sessionStorage),window.sessionStorage.setItem("pasCookieBuster",a))}}catch(b){storageAvailableResolved=-1}}function clearSessionStorage(a){var b=Object.keys(a),c;for(c in b)b[c].startsWith("pas[")&&a.removeItem(b[c])}
function cookieBusterValue(){var a=document.cookie.split(";"),b;for(b in a)if(a[b].trim().startsWith("pasCookieBuster="))return a[b].split("=")[1];return""}function isPostMessagesDisabled(){return 1==iapiConf.postMessagesDisabled}
function iapiAppendContextParameters(a){iapiConf=iapiConf||[];iapiLoginModeDownload?iapiConf.clientPlatform="download":iapiConf.clientPlatform||(iapiConf.clientPlatform="flash");for(var b="clientType clientPlatform clientVersion clientSkin clientChannel callId gameType gameTypePrefix softSerial deviceId deliveryPlatform deviceType osName osVersion deviceBrowser languageCode deviceFamily launchAlias".split(" "),c=0;c<b.length;c++){var d=b[c];iapiConf[d]&&(a=iapiAddUrlParams(a,d+"="+iapiConf[d]))}return a}
function iapiJsonp(a,b){scriptElement=document.createElement("SCRIPT");scriptElement.type="text/javascript";scriptElement.src=encodeURL(a)+"&jsoncallback="+b+"&responseType=json";document.getElementsByTagName("HEAD")[0].appendChild(scriptElement)}function iapiGet(a,b){if(a=document.getElementById(a))a.src=encodeURL(b)}function iapiAddUrlParams(a,b){a=0<a.indexOf("?")?a+"&":a+"?";return a+b}
function iapiLoginFailedActions(a){iapiPassword=null;iapiLoginSuccess=!1;iapiSessionValid=0;var b=a.errorCode;iapiWriteClientCookie("loginSuccess=0&errorCode="+b,iapiRealMode);iapiCalloutFunctions.login&&setTimeout(function(){iapiCalloutFunctions.login(0,0,b,iapiRealMode)},iapiEVENT_TIMER);iapiCalloutFunctions[iapiCALLOUT_LOGIN]&&setTimeout(function(){iapiCalloutFunctions[iapiCALLOUT_LOGIN](a)},iapiEVENT_TIMER);iapiLoginModeDownload&&iapiDownloadHtcmd(0,0,b,"");iapiCheckNextLogin()}
function iapiTokenFailedActions(a){iapiCalloutFunctions.temporarytoken&&setTimeout(function(){iapiCalloutFunctions.temporarytoken(0,null)},iapiEVENT_TIMER);iapiCalloutFunctions[iapiCALLOUT_TEMPORARYTOKEN]&&setTimeout(function(){iapiCalloutFunctions[iapiCALLOUT_TEMPORARYTOKEN](a)},iapiEVENT_TIMER);iapiLoginModeDownload&&iapiDownloadHtcmd(1,iapiSessionValid,0,"")}
function iapiCheckNextLogin(){if(null!=iapiNextLogin){var a=iapiNextLogin[0],b=iapiNextLogin[1],c=iapiNextLogin[2],d=iapiNextLogin[3],e=iapiNextLogin[4];iapiNextLogin=null;setTimeout(function(){iapiLogin(a,b,c,d,e)},iapiEVENT_TIMER)}}function iapiDownloadHtcmd(a,b,c,d){a&&d&&(a="htcmd:login?username="+encodeURIComponent(iapiUsername),a=a+"&password="+encodeURIComponent(d),a=a+"&realmode="+iapiRealMode,document.location=a+"&type=3")}
function iapiRedirectCallback(a){var b=String(a.requestId),c=iapiGetRequest(b);if(c){var d=c[1],e=null;try{e=JSON.parse(a.redirectResponse)}catch(f){}e.sessionRef&&isStorageAvailable()&&window.sessionStorage.setItem(getSessionKey("sessionRef"),e.sessionRef);b={errorCode:6,errorText:"Invalid response.",playerMessage:""};e?b=e.errorCode?{errorCode:e.errorCode,errorText:e.errorText,playerMessage:e.playerMessage}:null:e=b;if(b&&6==b.errorCode&&c[3].length<iapiConf.loginDomainRetryCount){b=(new Date).getTime()+
Math.round(1E6*Math.random());var g=setTimeout("iapiRequestFailed("+b+")",1E3*iapiConf.loginDomainRetryInterval);iapiRegisterRequestId(b,d,g,c[3],c[4],c[5])}else if(d==iapiCALLOUT_LOGIN)if(null==b){iapiPassword=null;iapiLoginSuccess=!0;iapiError=null;iapiSessionValid=1;if(c=e.sessionValidationData)for(g in Object.keys(c))if("SessionValidationByGeolocationData"!==c[g]){iapiSessionValid=0;break}iapiWriteClientCookie("loginSuccess=1&sessionValid="+iapiSessionValid+"&loginDomain="+iapiConf.loginServer,
iapiRealMode);iapiCalloutFunctions.login&&setTimeout(function(){iapiCalloutFunctions.login(1,iapiSessionValid,0,iapiRealMode)},iapiEVENT_TIMER);iapiCalloutFunctions[iapiCALLOUT_LOGIN]&&setTimeout(function(){iapiCalloutFunctions[iapiCALLOUT_LOGIN](e)},iapiEVENT_TIMER);iapiLoginModeDownload?iapiSessionValid?iapiRequestTemporaryToken(iapiRealMode):iapiDownloadHtcmd(1,0,0,""):iapiLoginModeFlash&&iapiSessionValid&&(c="real",iapiRealMode||(c="fun"),iapiLaunchClient(iapiFlashLoginClientType,iapiFlashLoginGameType,
c));iapiCheckNextLogin()}else iapiError=b,iapiLoginFailedActions(e);else d==iapiCALLOUT_TEMPORARYTOKEN?null==b&&e.sessionToken&&e.sessionToken.sessionToken?(iapiCalloutFunctions.temporarytoken&&setTimeout(function(){iapiCalloutFunctions.temporarytoken(1,e.sessionToken.sessionToken)},iapiEVENT_TIMER),iapiCalloutFunctions[iapiCALLOUT_TEMPORARYTOKEN]&&setTimeout(function(){iapiCalloutFunctions[iapiCALLOUT_TEMPORARYTOKEN](e)},iapiEVENT_TIMER),iapiLoginModeDownload&&iapiDownloadHtcmd(1,1,0,e.sessionToken.sessionToken)):
iapiTokenFailedActions(e):iapiCalloutFunctions[d]&&setTimeout(function(){iapiCalloutFunctions[d](e)},iapiEVENT_TIMER)}}
function iapiRequestFailed(a){if(a=iapiGetRequest(a)){var b=a[1];if(!iapiMakeRedirectRequest(a[4],a[5],b,a[3])){var c={errorCode:6,errorText:"Request timed out.",playerMessage:""};b==iapiCALLOUT_LOGIN?iapiCalloutFunctions[iapiCALLOUT_LOGIN]&&iapiLoginFailedActions(c):b==iapiCALLOUT_TEMPORARYTOKEN?iapiCalloutFunctions[iapiCALLOUT_TEMPORARYTOKEN]&&iapiTokenFailedActions(c):iapiCalloutFunctions[b]&&setTimeout(function(){iapiCalloutFunctions[b](c)},iapiEVENT_TIMER)}}}
function iapiRegisterRequestId(a,b,c,d,e,g){iapiRequestIds.push([a,b,c,d,e,g])}function iapiGetRequest(a){for(var b in iapiRequestIds)if(arr=iapiRequestIds[b],arr[0]==a)return iapiRequestIds.splice(b,1),arr[2]&&clearTimeout(arr[2]),(a=document.getElementById(iapiIframename+"_"+a))&&!a.dataset.reusable&&document.getElementById(iapiDivname).removeChild(a),arr;return null}
function iapiClearRedirectRequests(a,b){for(var c=0;c<iapiRequestIds.length;){arr=iapiRequestIds[c];if(arr[1]==a){var d=0;0<arr[4].indexOf("realMode=1")&&(d=1);if(d==b){iapiRequestIds.splice(c,1);arr[2]&&clearTimeout(arr[2]);(d=document.getElementById(iapiIframename+"_"+arr[0]))&&document.getElementById(iapiDivname).removeChild(d);continue}}c++}}function iapiHasRedirectRequest(a){for(var b=0;b<iapiRequestIds.length;){arr=iapiRequestIds[b];if(arr[1]==a)return!0;b++}return!1}
function initMessageListener(){window.postMessage&&(window.addEventListener?(window.addEventListener("message",iapiOnMessage,!1),iapiMessagesSupported=!0):window.attachEvent&&(window.attachEvent("onmessage",iapiOnMessage),iapiMessagesSupported=!0))}
function iapiOnMessage(a){if(a.origin){var b=iapiConf.loginServer.split("|"),c=a.origin.replace(getHttpProtocol()+"://","");c=b.indexOf(c);if(a.origin==getHttpProtocol()+"://"+b[c]){var d=a.data.split("&");b=[];for(c=0;c<d.length&&1E3>c;c++){var e=d[c].indexOf("=");0<e&&(b[d[c].substring(0,e)]=decodeURIComponent(d[c].substring(e+1).replace(/\+/g,"%20")))}if(b.redirectResponse&&0<b.redirectResponse.indexOf("requestId"))try{b.requestId=JSON.parse(b.redirectResponse).requestId}catch(g){}if(!b.requestId&&
(d=document.getElementById(iapiDivname)))for(c=0;c<d.childNodes.length&&1E3>c;c++)if(d.childNodes[c].contentWindow==a.source){if(a=d.childNodes[c].dataset.requestId){b.requestId=a;break}a=d.childNodes[c].id.split("_");1<a.length&&(b.requestId=a[1]);break}iapiMessagesAnswered=!0;iapiRedirectCallback(b)}}}
function iapiGetCookie(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}function encodeHTML(a){var b=document.createElement("div");a=document.createTextNode(a);b.appendChild(a);return b.innerHTML.replace(/'/g,"&#39;")}
function encodeURL(a){a=JSON.stringify(a);a=a.substring(1,a.length-1);a=removeHex(a);return a.match(/^http/gi)?a.replace(/</g,"%3C").replace(/>/g,"%3E").replace(/"/g,"%22").replace(/'/g,"%27"):""}function removeHex(a){return a.replace(/&#(\d+);/g,"").replace(/&#x([A-Za-z0-9]+);/g,"")}
Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){if(null==this)throw new TypeError('"this" is null or not defined');var c=Object(this),d=c.length>>>0;if(0===d)return-1;b=+b||0;Infinity===Math.abs(b)&&(b=0);if(b>=d)return-1;for(b=Math.max(0<=b?b:d-Math.abs(b),0);b<d;){if(b in c&&c[b]===a)return b;b++}return-1});
function getCurrentDomain(){if(self.$currentDomain)return self.$currentDomain;for(var a=0,b=document.domain,c=b.split("."),d="_gd"+(new Date).getTime();a<c.length-1&&-1==document.cookie.indexOf(d+"="+d);)b=c.slice(-1-++a).join("."),document.cookie=d+"="+d+";domain="+b+";";document.cookie=d+"=;expires=Thu, 01 Jan 1970 00:00:01 GMT;domain="+b+";";return self.$currentDomain=b}"undefined"!==typeof iapiJsLoaded&&iapiJsLoaded();function isSecureAttr(){return"false"==iapiConf.setSecureAttr?!1:!0}
function getHttpProtocol(){return isSecureAttr()?"https":"http"}function isDeviceAtlasEnabled(){return!iapiConf.disableDeviceAtlasIntegration}var deviceAtlasScripts=[],DeviceAtlas={cacheType:"none"};if(isDeviceAtlasEnabled())try{deviceAtlasScripts.push(loadJs("dacs.js").catch(function(){}),loadJs("clientHintHeaders.js").catch(function(){}))}catch(a){}
function loadJs(a){return new Promise(function(b,c){var d=document.createElement("script");d.src=getHttpProtocol()+"://"+iapiConf.loginServer+"/jswrapper/"+a;d.type="text/javascript";d.async=!0;d.onerror=function(e){c(e)};d.onload=function(){b()};window.document.head.appendChild(d)})}
;
